
export const PRICE_INCREASED = "PRICE_INCREASED";
export const PRICE_DECREASED = "PRICE_DECREASED";

export type PRICE_INCREASED = typeof PRICE_INCREASED;
export type PRICE_DECREASED = typeof PRICE_DECREASED;

export type PRICE_STATUS = PRICE_DECREASED | PRICE_INCREASED;
